### ISSUE TITLE
Re-render calendar on data update

### ISSUE THREAD

**Issue by Hakonwibergh** [mpachnis/mp-calendar#7] opened 2018-11-06 11:59 UTC
Hi!
I'm using this component with Polymer 2 but I can't the calendar to update on data change.

Im fetching data from database, but **data is not displayed in calendar until I swap to a different month and then back to the correct month.**

Any plans of adding a feature to re-render the calendar if new data is presented to events-object? :)

**Comment by mpachnis** [comment] 2018-11-06 18:55
Hi Hakonwibergh,

the events-object has an observer so when you change the data, it will automatically re-render the calendar with the new events.

Do you have any error in the console, can you share a demo?

**Comment by Hakonwibergh** [comment] 2018-11-07 08:16
Hi @mpachnis !
I got it working by loading all events earlier and filter through them when needed.

Im using Firebase and Polymer 2, but still having issues when fetching new values from firebase and putting it onto the events-object. No console errors.

Im not able to provide a demo at this time, but I will see if I can get the time to put something together.

**Comment by mpachnis** [comment] 2018-11-12 17:29
Any luck with the demo?

**Comment by mpachnis** [comment] 2018-12-11 19:22
I'm going to close this as I can't reproduce it. Feel free to re-open if you can provide a demo.

**Closed by mpachnis** 2018-12-11 19:22 UTC
